{"name": "test_case02", "status": "failed", "statusDetails": {"message": "AssertionError: assert 10 == 20", "trace": "self = <Allure_report1.test_file01.Test_Suite01 object at 0x0378B910>\n\n    def test_case02(self):\n        print(\"Hello, Am from test case 02\")\n        i=10\n>       assert i==20\nE       assert 10 == 20\n\ntest_file01.py:25: AssertionError"}, "attachments": [{"name": "stdout", "source": "7301bf3c-aef2-4f2a-8cd3-95079d8219b7-attachment.txt", "type": "text/plain"}], "start": 1577337427391, "stop": 1577337427391, "uuid": "026a268c-8a29-4d92-86b0-2b7f8690d8db", "historyId": "fae923919d3d5f28489b2cff89fab9ab", "testCaseId": "1033e4a43a4fe4123d508aafdfc8fab3", "fullName": "test_file01.Test_Suite01#test_case02", "labels": [{"name": "suite", "value": "test_file01"}, {"name": "subSuite", "value": "Test_Suite01"}, {"name": "host", "value": "com2"}, {"name": "thread", "value": "6308-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_file01"}]}